(define (problem visitall-assistance_problem_30_prime)
  (:domain visitall-assistance_prime)
  (:objects
    node1 node2 node3 node4 node5 node6 node7 node8 node9 node10 node11 node12  - place)
    

  (:init
    (connected node1 node2)
    (connected node1 node3)
    (connected node1 node11)
    (connected node2 node3)
    (connected node2 node11)
    (connected node3 node1)
    (connected node3 node4)
    (connected node4 node5)
    (connected node4 node7)
    (connected node5 node6)
    (connected node5 node8)
    (connected node5 node9)
    (connected node6 node5)
    (connected node6 node7)
    (connected node6 node8)
    (connected node7 node3)
    (connected node7 node8)
    (connected node7 node10)
    (connected node8 node9)
    (connected node9 node8)
    (connected node9 node10)
    (connected node10 node1)
    (connected node10 node8)
    (connected node10 node11)
    (connected node11 node3)
    (connected node11 node6)
    (connected node11 node8)
    (connected node11 node12)
    (connected node12 node9)

    (at-prime node9)
    (visited node9)

    (= (total-cost) 0)
  )


  (:goal (and 
    (visited node1)
    (visited node2)
    (visited node3)
    (visited node4)
    (visited node5)
    (visited node6)
    (visited node7)
    (visited node8)
    (visited node10)
    (visited node11)
    (visited node12)
  ))
  (:metric minimize (total-cost))

)