(define (problem visitall-assistance_problem_45_prime)
  (:domain visitall-assistance_prime)
  (:objects
    node1 node2 node3 node4 node5 node6 node7 node8 node9 node10 node11 node12 node13 node14  - place)
    

  (:init
    (connected node1 node2)
    (connected node1 node6)
    (connected node1 node9)
    (connected node2 node3)
    (connected node2 node13)
    (connected node3 node4)
    (connected node3 node6)
    (connected node3 node13)
    (connected node4 node5)
    (connected node4 node10)
    (connected node5 node1)
    (connected node5 node6)
    (connected node6 node3)
    (connected node6 node5)
    (connected node6 node7)
    (connected node7 node2)
    (connected node7 node8)
    (connected node8 node9)
    (connected node8 node10)
    (connected node8 node12)
    (connected node9 node10)
    (connected node10 node1)
    (connected node10 node11)
    (connected node11 node12)
    (connected node12 node13)
    (connected node13 node2)
    (connected node13 node9)
    (connected node13 node14)
    (connected node14 node3)
    (connected node14 node9)

    (at-prime node13)
    (visited node13)

    (= (total-cost) 0)
  )


  (:goal (and 
    (visited node1)
    (visited node2)
    (visited node3)
    (visited node4)
    (visited node5)
    (visited node6)
    (visited node7)
    (visited node8)
    (visited node9)
    (visited node10)
    (visited node11)
    (visited node12)
    (visited node14)
  ))
  (:metric minimize (total-cost))

)